"""
The script takes the recommendation result file generated by session_rec baselines and recombine
it with the recommendation test data that is used to run the baselines, and finally
generates a copy of the recommendation test data, appended with a new column containing the prediction items
for each test sample.
"""
import csv
import json
from pathlib import Path
import pickle

TEST_PATH = Path('./session_rec_sigir_data/test/rec_test.json')
TEST_WITH_PREDICTION_PATH = Path('./session_rec_sigir_data/test/rec_test_with_pred.json')
RECOMMENDATION_PATH = Path('./session_rec_sigir_data/prepared/test_single_models_sigir.stamp-init_lr=0.003-n_epochs=10-decay_rate=0.4.csv.Saver@20--.csv')
ITEM_LABEL_ENCODING_MAP_PATH = Path('./session_rec_sigir_data/prepared/item_label_encoding.p')

item_label_encoding = pickle.load(ITEM_LABEL_ENCODING_MAP_PATH.open(mode='rb'))

with TEST_PATH.open() as f:
    original_test_data = json.load(f)

for d in original_test_data:
    d['prediction'] = []

with RECOMMENDATION_PATH.open() as csvfile:
    reader = csv.DictReader(csvfile, delimiter=";")
    for row in reader:
        idx_in_test_data = int(row['SessionId'])
        recommendation_i = list(map(int, row['Recommendations'].split(',')))
        recommendation_s = [item_label_encoding[i] for i in recommendation_i]
        original_test_data[idx_in_test_data]['prediction'] = recommendation_s

# store the final output file
with TEST_WITH_PREDICTION_PATH.open('w') as outfile:
    json.dump(original_test_data, outfile)

print("All done appending prediction to original recommendation test data!")
